apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-acidentes
spec:
  selector:
    matchLabels:
      app: backend-acidentes
  template:
    metadata:
      labels:
        app: backend-acidentes
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: backend-acidentes
        image: pmdferreira/patient-care:acidentesv1
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        
