apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-acidentes
spec:
  selector:
    matchLabels:
      app: backend-acidentes
  template:
    metadata:
      labels:
        app: backend-acidentes
    spec:
      containers:
      - name: backend-acidentes
        image: patient-care/acidentesv1:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullSecrets:
        - name: secretpat
