apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-acidentes
spec:
  selector:
    matchLabels:
      app: backend-acidentes
  template:
    metadata:
      labels:
        app: backend-acidentes
    spec:
      imagePullSecrets:
      - name: secretpat
      containers:
      - name: backend-acidentes
        image: pmdferreira/patient-care:acidentesv5
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: acidentes-service
spec:
  selector:
    app: backend-acidentes
  ports:
  - port: 80
    targetPort: 5000

        
