apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirthconnect
  namespace: mirth-sys
spec:
  selector:
    matchLabels:
      app: mirthconnect
  template:
    metadata:
      labels:
        app: mirthconnect
    spec:
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: mirth-vol
      containers:
      - name: mirthconnect
        image: nextgenhealthcare/connect:3.12
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
          - mountPath: /custom-lib
            name: data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mirth-vol
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-service
  namespace: mirth-sys
spec:
  selector:
    app: mirthconnect
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-service-https
  namespace: mirth-sys
spec:
  type: LoadBalancer
  selector:
    app: mirthconnect
  ports:
  - port: 443
    targetPort: 8443
