apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirthconnect
  namespace: mirth-sys
spec:
  selector:
    matchLabels:
      app: mirthconnect
  template:
    metadata:
      labels:
        app: mirthconnect
    spec:
      containers:
      - name: mirthconnect
        image: nextgenhealthcare/connect:3.12
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
            - mountPath: /custom-lib/
              name: custom-lib
        volumes:
          - emptyDir: {}
            name: custom-lib
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mirthconnect
  name: mirth-pvc
  namespace: mirth-sys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-service
  namespace: mirth-sys
spec:
  selector:
    app: mirthconnect
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mirth-service-https
  namespace: mirth-sys
spec:
  type: LoadBalancer
  selector:
    app: mirthconnect
  ports:
  - port: 443
    targetPort: 8443
